/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    //kotlin("jvm") version "1.8"
    id("buildlogic.java-conventions")
    id("com.gradleup.shadow") version "8.3.5"
}

group = "net.citizensnpcs"
version = "2.0.36-SNAPSHOT"
val craftbukkitVersion = "1.21.3-R0.1-SNAPSHOT"

repositories {
    mavenCentral()
    maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    maven("https://oss.sonatype.org/content/repositories/snapshots/")
    maven("https://maven.citizensnpcs.co/repo") {
        name = "citizens-repo"
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

dependencies {
    api(libs.net.citizensnpcs.citizensapi)
    compileOnly(project(":citizens-main"))
    compileOnly("org.spigotmc:spigot:$craftbukkitVersion:remapped-mojang")
}

tasks {
    compileJava {
        options.compilerArgs.add("-Xlint:deprecation")
        options.compilerArgs.add("-Xlint:unchecked")
        options.encoding = "UTF-8"
        sourceCompatibility = "21"
        targetCompatibility = "21"
    }

    jar {
        manifest {
            attributes(
                "Implementation-Title" to project.name,
                "Implementation-Version" to project.version
            )
        }
    }

    val remapObf by creating {
        group = "build"
        doLast {
            println("Executing remap-obf...")
            // Add your remap logic or integrate SpecialSource here.
        }
    }

    val remapSpigot by creating {
        group = "build"
        dependsOn(remapObf)
        doLast {
            println("Executing remap-spigot...")
            // Add additional remap logic here.
        }
    }

    shadowJar {
        archiveClassifier.set("all")
        relocate("org.example", "net.citizensnpcs.relocated") // Replace with actual relocations
    }
}
