/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "citizens-parent"
include(":citizens")
include(":citizens-main")
include(":citizens-v1_21_R2")
project(":citizens").projectDir = file("dist")
project(":citizens-main").projectDir = file("main")
project(":citizens-v1_21_R2").projectDir = file("v1_21_R2")
